name: CI for Quantum-Teleportation sdirg3 project

on: pull_request

jobs:
    setup:
        name: Setup project
        runs-on: ubuntu-24.04
        env:
            CC: clang
            CXX: clang++
        steps:
            - uses: actions/checkout@v3
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake ninja-build qt6-base-dev llvm build-essential
            - run: /bin/bash .ci/setup.sh
            - name: Cache cmake and third party
              uses: actions/upload-artifact@v3
              with:
                name: cmake_cache
                path: |
                  build
    format-check:
        needs: setup
        name: Check clang-format
        runs-on: ubuntu-24.04
        env:
            CC: clang
            CXX: clang++
        steps:
            - uses: actions/checkout@v3
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: cmake_cache
                path: |
                  build
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build clang-format qt6-base-dev
            - run: /bin/bash .ci/format_check.sh
    tidy-check:
        needs: setup
        name: Check clang-tidy
        runs-on: ubuntu-24.04
        env:
            CC: clang
            CXX: clang++
        steps:
            - uses: actions/checkout@v3
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: cmake_cache
                path: |
                  build
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build clang-tidy qt6-base-dev
            - run: /bin/bash .ci/tidy_check.sh
      build-check:
        needs: setup
        name: Check buildability
        runs-on: ubuntu-24.04
        env:
            CC: clang
            CXX: clang++
        steps:
            - uses: actions/checkout@v3
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: cmake_cache
                path: |
                  build
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build llvm build-essential qt6-base-dev
            - run: /bin/bash .ci/build_check.sh

